### ISSUE TITLE
Cannot build without fimagestore

### ISSUE THREAD

**Issue by jkloe** [Transkribus/fimagestoreClient#4]
When building the client  with `mvn clean install` it throws this error:

`Could not resolve dependencies for project org.dea.fimagestore:fimagestore-http-client:jar:0.3: Failed to collect dependencies at org.dea.fimagestore:fimagestore-core:jar:1.1: Failed to read artifact descriptor for org.dea.fimagestore:fimagestore-core:jar:1.1: Could not find artifact org.dea.fimagestore:fimagestore:pom:1.1 in dea-artifactory (http://dbis-halvar.uibk.ac.at/artifactory/libs-release/)`

So fimagestore-core soemhow depends on fimagestore which is not on the artifactory.

**Comment by kahlep** [comment]
Required parts of FImagestore are deployed to artifactory on updates.
